#!/bin/bash

source ./constants.sh

if [ -f $FUNCTIONS ];
then
	
	source $ICONS;
	source $COLORS;
	source $FUNCTIONS;
fi

if [ -d $DIR ];
then 
    gitoptions;
else
	echo "Oops! not a valid git directory. This script is helpful for automating some git operations.";
	echo "Please use this script in the valid git directory!";
	exit;
fi
