#!/bin/bash

#!/bin/bash

##
## Colours
##
BLACK='\e[30m'          # Black
RED='\e[31m'            # Red
GREEN='\e[32m'          # Green
YELLOW='\e[33m'         # Yellow
BLUE='\e[34m'           # Blue
MAGENTA='\e[35m'        # Magenta
CYAN='\e[36m'           # Cyan
LIGHTGREY='\e[37m'      # Light grey
DARKGREY='\e[90m'       # Dark grey
LIGHTRED='\e[91m'       # Light red
LIGHTGREEN='\e[92m'     # Light green
LIGHTYELLOW='\e[93m'    # Light yellow
LIGHTBLUE='\e[94m'      # Light blue
LIGHTRED='\e[95m'       # Light magenta
LIGHTCYAN="\e[96m"      # Light Cyan
WHITE='\e[97m'          # White
BOLD='\e[1m'
NOCOLOUR='\e[0m'

#printf "${CYAN}##############################################################################################################################\n";
#printf "${GREEN}#####			 Project: autogit									########\n";
#printf "${GREEN}#####			 Author: Murali Prasanth N							########\n";
#printf "${GREEN}#####			 date: 	20/02/2017									########\n";
#printf "${CYAN}###############################################################################################################################\n";

source ./git_functions

echo "\033[36mWhat you want to do?"
echo "\n"
echo "\033[36m1. Git Branch "
echo "\033[31m2. Git Log"
echo "\033[32m3. Git Delete"
echo "\033[33m4. Git Merge or Rebase"
echo "\033[34m5. Git Tag"
echo "\033[35m6. Git Status"

read NUM

case $NUM in
	1) branch ;;
	2) Log ;;
	3) Delete ;;
	4) echo "four" ;;
	5) echo "five" ;;
	6) echo "six" ;;
	7) echo "seven" ;;
	8) echo "eight" ;;
	9) echo "nine" ;;
	10) echo "ten" ;;
	*) echo "INVALID NUMBER!" ;;
esac
