#!/bin/bash

#!/bin/bash

##
## Colours
##
BLACK='\e[30m'          # Black
RED='\e[31m'            # Red
GREEN='\e[32m'          # Green
YELLOW='\e[33m'         # Yellow
BLUE='\e[34m'           # Blue
MAGENTA='\e[35m'        # Magenta
CYAN='\e[36m'           # Cyan
LIGHTGREY='\e[37m'      # Light grey
DARKGREY='\e[90m'       # Dark grey
LIGHTRED='\e[91m'       # Light red
LIGHTGREEN='\e[92m'     # Light green
LIGHTYELLOW='\e[93m'    # Light yellow
LIGHTBLUE='\e[94m'      # Light blue
LIGHTRED='\e[95m'       # Light magenta
LIGHTCYAN="\e[96m"      # Light Cyan
WHITE='\e[97m'          # White
BOLD='\e[1m'
NOCOLOUR='\e[0m'

#printf "${CYAN}##############################################################################################################################\n";
#printf "${GREEN}#####			 Project: autogit									########\n";
#printf "${GREEN}#####			 Author: Murali Prasanth N							########\n";
#printf "${GREEN}#####			 date: 	20/02/2017									########\n";
#printf "${CYAN}###############################################################################################################################\n";


echo "\033[36mChoose an option from the below list?"